name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    environment: preview
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        env:
          VITE_CLIENT_ID: ${{ secrets.VITE_CLIENT_ID }}
          VITE_CLIENT_URL: ${{ secrets.VITE_CLIENT_URL }}
          VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}
          VITE_DEMO_API: ${{ secrets.VITE_DEMO_API }}
          PORT: ${{ secrets.PORT }}
          CLIENT_URL: ${{ secrets.CLIENT_URL }}
          SERVER_URL: ${{ secrets.SERVER_URL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DB_CONNECT: ${{ secrets.DB_CONNECT }}
        uses: cypress-io/github-action@v5
        with:
          start: npm run client, npm run server
          working-directory: unit_tests/cypress
          wait-on: , 